language: php
php:
   - '7.1'

services:
   - mysql

script:
    - composer install
    - php bin/console doctrine:database:create
    - php bin/console doctrine:schema:create --env=test
    - php bin/console doctrine:fixtures:load --no-interaction --no-debug --env=test
    - phpunit
