language: php
php:
- '7.1'
services:
- mysql
script:
- composer install
- php bin/console doctrine:database:create
- php bin/console doctrine:schema:create --env=test
- php bin/console doctrine:fixtures:load --no-interaction --no-debug --env=test
- phpunit
deploy:
  provider: heroku
  api_key:
    secure: egKXjVPT8/lIKbYjmK9RvO6+ugcLER6RN2EJNQBMd/uonn/OUmORDEPIbWbWzy5IXPqUeW4e1VhPXEg9lKG+Pcxa40SHyDPdJ1+M8zLT7wv+lEStwWnagP4fTRU8SKaZoDpCpbUnF8SFv2le8KDU00KwsKRR/shu+T6WhIAL0tgPYD5mCMw3rNOxKN5OyWSdPZXWDAaQjNqgraVQUdIl/ZL/4d20Zf7ymmBV/k59msf0qdrIK41Ti/L3VgO8z6McwrMC2FSN1vW6MOPHMUbgIGY/RQvYgbzO/xSiDWcnA/EflMf+iUOfo0UvHykUCaQxl+Kmy+lNFZ8w9Uj+qo/IP2EJ60BzoOPkDn7lNuQrlbeqdo/l9HgqBRkts50bLs5d83aRVz9N/dzPIfRibRVcRUkObC9wCNIPbxz6MLdFmn1uhiBgNSkAgiBwu383G4ASYhHtwkCuBuPmGRzBo0ZAfHD78w0ZSKwSJ81Lj2z+I6o5TD7jAdH/D41wfq8XqWa1XxgsyMygh1yia6rQkoLnohjGczDkNQuCiDiU4Sx9K4i4U/5SCJOpFyUGpD40HVWpZ/vyVly21JYSjFbEkttPelvyvCXGurpVNEc9TikXn/vf/FKVHSGjFZr+eL3F5ukrfULgevs6nE9FDC6DLOT8j2XyZtKlqC5wi2jcqKtj/jY=
  app: planificateur-de-course
  on:
    repo: fromdanut/planificateur_course
