# Config for heroku site.

imports:
    - { resource: config.yml }

# see https://www.tiloweb.com/php/symfony/deployer-symfony-sur-heroku-integration-continue
# 
monolog:
    handlers:
        nested:
            type:  stream
            path:  "php://stderr"
            level: debug
#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc
