# Config for heroku site.

imports:
    - { resource: config.yml }


monolog:
    handlers:
        nested:
            path: 'php://stderr' # Specifif for logs with heroku
#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc
