<?php

namespace UserBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findJean()
    {
        $qb = $this->createQueryBuilder('u')
                   ->where('u.id LIKE :username')
                   ->setParameter('username', '%fred%');
        return $qb
          ->getQuery()
          ->getSingleResult();
    }
}
