<?php

namespace PC\PlatformBundle\Repository;

/**
 * CategoryIngredientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryIngredientRepository extends \Doctrine\ORM\EntityRepository
{
}
