<?php

namespace PC\PlatformBundle\Repository;

/**
 * RecipeSearchOptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecipeSearchOptionRepository extends \Doctrine\ORM\EntityRepository
{
}
