<?php

namespace PC\PlatformBundle\Repository;

/**
 * RecipeIngredientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecipeListOptionRepository extends \Doctrine\ORM\EntityRepository
{
}
