<?php

namespace PC\PlatformBundle\Repository;
use PC\PlatformBundle\Entity\RecipeListOption;
use PC\PlatformBundle\Entity\ShoppingListOption;
use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * RecipeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecipeRepository extends \Doctrine\ORM\EntityRepository
{
    /*
        Permet de charger l'image des recette.
    */
    public function withImage(QueryBuilder $qb)
    {
      $qb
        ->leftJoin('r.image', 'image')
        ->addSelect('image')
      ;
    }

    /*
        Applique un ensemble de clause Where en fonction des $option :
        ajoute les condition communes : correspondant aux attributs de l'entity RecipeOption.
        Puis, en fonction du type d'instance du parametre $option rajoute
        les conditions correspondant aux attributs de l'instance.
    */
    public function byOption(QueryBuilder $qb, $option)
    {
        if ($option->getQuick()) {
            $qb->where('r.cookingTime < 20');
        }

        if ($option->getEco()) {
            $qb->andWhere('r.price < 10');
        }

        if ($option->getDiet()) {
            $qb->andWhere('r.calorie < 15000');
        }

        $qb->andWhere('r.rating >= :rating')
        ->setParameter('rating', $option->getRating());

        if ($option instanceof ShoppingListOption) {
            // Limité au nombre de repas voulu par l'utilisateur.
            $qb->setMaxResults($option->getNbMeal());
        }

        elseif ($option instanceof RecipeListOption) {
            // Filtre par mot clé.
            if ($option->getKeyword() ==! null) {
                $qb->andWhere('r.name LIKE :exp')
                ->setParameter('exp', '%'.$option->getKeyword().'%');
            }
        }
    }

    /*
        Permet de faire une pagination.
    */
    public function findByOptionPaginated($option, $page, $nbPerPage)
    {
        $qb = $this->createQueryBuilder('r');
        $this->withImage($qb);
        $this->byOption($qb, $option);
        $query = $qb->getQuery();

        $query
          // On définit l'annonce à partir de laquelle commencer la liste
          ->setFirstResult(($page-1) * $nbPerPage)
          // Ainsi que le nombre d'annonce à afficher sur une page
          ->setMaxResults($nbPerPage)
          ;

        return new Paginator($query, true);
    }

    public function findByOption($option)
    {
        $qb = $this->createQueryBuilder('r');
        $this->withImage($qb);
        $this->byOption($qb);

        return $qb
          ->getQuery()
          ->getResult()
        ;
    }

    /*
        int id
        int nb
        return list of recipe Entity
    */
    public function findSuggestions($id, $nb)
    {
        /*
            comportement attendu :
            récupère l'auteur ou le titre de la recette
            retourne n ($nb) like titre ou auteur.
        */
        $qb = $this->createQueryBuilder('r');
        $qb->setMaxResults($nb);

        return $qb
            ->getQuery()
            ->getResult();
    }
}
