<?php

namespace PC\PlatformBundle\Repository;

/**
 * ShoppingListOptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShoppingListOptionRepository extends \Doctrine\ORM\EntityRepository
{
}
