<?php

namespace PC\PlatformBundle\Repository;

/**
 * ShoppingListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShoppingListRepository extends \Doctrine\ORM\EntityRepository
{
    // Méthode pour débug à supprimer...
    public function findOnlyOne()
    {
        $qb = $this->createQueryBuilder('s');
        return $qb
          ->getQuery()
          ->getSingleResult();
    }

}
